<!doctype html><html lang=en><head><title>프로그래머스에서 정답이 맞는데 아무리 해도 Test Case에서 오류나는 경우 &ndash; litsynp.log</title><meta name=description content><meta name=viewport content="width=device-width,initial-scale=1"><meta charset=utf-8><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin=anonymous><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/academicons/1.9.1/css/academicons.min.css integrity="sha512-b1ASx0WHgVFL5ZQhTgiPWX+68KjS38Jk87jg7pe+qC7q9YkEtFq0z7xCglv7qGIs/68d3mAp+StfC8WKC5SSAg==" crossorigin=anonymous><link rel=stylesheet href=https://blog.litsynp.com/css/palettes/base16-dark.css><link rel=stylesheet href=https://blog.litsynp.com/css/risotto.css><link rel=stylesheet href=https://blog.litsynp.com/css/custom.css><link rel=icon href=https://blog.litsynp.com/favicon.ico></head><body><div class=page><header class=page__header><nav class="page__nav main-nav"><ul><h1 class=page__logo><a href=https://blog.litsynp.com/ class=page__logo-inner>litsynp.log</a></h1><li class=main-nav__item><a class=nav-main-item href=https://blog.litsynp.com/posts title>posts</a></li><li class=main-nav__item><a class=nav-main-item href=https://blog.litsynp.com/tags title>tags</a></li><li class=main-nav__item><a class=nav-main-item href=https://blog.litsynp.com/categories title>categories</a></li><li class=main-nav__item><a class=nav-main-item href=https://blog.litsynp.com/series title>series</a></li></ul></nav></header><section class=page__body><header class=content__header><h1>프로그래머스에서 정답이 맞는데 아무리 해도 Test Case에서 오류나는 경우</h1></header><div class=content__body><h1 id=프로그래머스에서-정답이-맞는데-아무리-해도-test-case에서-오류나는-경우>프로그래머스에서 정답이 맞는데 아무리 해도 Test Case에서 오류나는 경우</h1><p>프로그래머스에서 문제를 푸는데 아무리 해도 정답이 맞지 않는 경우가 있다.</p><p>그건 어쩌면 logic이 틀린게 아니라 변수 초기화 시점이 잘못됐을 수도 있다.</p><p>static을 이용해 전역으로 설정하고 있었다면,</p><p><a href=https://programmers.co.kr/questions/13442>참고</a>를 보면 <code>answer = 0</code> 초기화를 선언 시가 아닌 <strong>solution 안에서 진행해야</strong> 테스트케이스 오류가 나지 않음을 알 수 있다.</p><p>추측으로는 이전의 테스트 케이스 진행 중 <code>answer</code> 의 값이 이전 테스트 케이스에서 영향을 받은 걸지도 모르겠다.</p><p>이런 식으로 실전에서 맞아야 할 몇 문제를 더 틀렸을 수도 있었을 것 같다&mldr;</p><p>주의 해야겠다!</p></div><footer class=content__footer></footer></section><section class=page__aside><div class=aside__about><div class=aside__about><h1 class=about__title>litsynp.log</h1></div><ul class=aside__social-links><li><a href=https://www.github.com/litsynp rel=me aria-label=GitHub title=GitHub><i class="fa-brands fa-github" aria-hidden=true></i></a>&nbsp;</li><li><a href=https://docs.litsynp.com rel=me aria-label=GitBook title=GitBook><i class="fa fa-book" aria-hidden=true></i></a>&nbsp;</li><li><a href=mailto:nocte55is@gmail.com rel=me aria-label=Email title=Email><i class="fa-solid fa-envelope" aria-hidden=true></i></a>&nbsp;</li><li><a href=/posts rel=me aria-label=Posts title=Posts><i class="fa fa-pencil-square" aria-hidden=true></i></a>&nbsp;</li></ul></div><hr><div class=aside__content><p>2022-04-28</p></div></section><section class=page__comments><script src=https://utteranc.es/client.js repo=litsynp/litsynp.github.io issue-term=pathname theme=github-dark crossorigin=anonymous async></script></section><footer class=page__footer><p></p><br><br><p class=copyright>© <a href=https://github.com/litsynp>litsynp</a>.</p><p class=advertisement>Powered by <a href=https://gohugo.io/>hugo</a> and <a href=https://github.com/joeroe/risotto>risotto</a>.</p></footer></div></body></html>